# ===============================
# = DataSource Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/DEV
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = GCP DataSource Configuration
# ===============================
#spring.datasource.url=jdbc:postgresql://34.10.95.77:5432/DEV
#spring.datasource.username=postgres
#spring.datasource.password=Postgres@17
#spring.datasource.driver-class-name=org.postgresql.Driver

